[package]
name = "odata-query"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_odata_query"
crate-type = ["cdylib"]

[dependencies]
base64 = "0.21.2"
nom = "7.1.3"
pyo3 = "0.18.3"
